services:
  - type: static
    name: aroma-data-frontend
    runtime: static
    repo: https://github.com/brunorochamczal/aroma_data
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_APP_ID
        sync: false  # Você define no dashboard do Render
      - key: VITE_TOKEN
        sync: false
      - key: VITE_AROMA_URL
        value: https://api.aroma.com  # URL do Aroma
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
