services:
  - type: web
    name: aroma-data-system
    runtime: node
    repo: https://github.com/brunorochamczal/aroma_data
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_AROMA_APP_ID
        value: SEU_APP_ID_AQUI
      - key: VITE_AROMA_URL
        value: https://api.aroma.com
      - key: VITE_AROMA_FUNCTIONS_VERSION
        value: latest
    healthCheckPath: /
    autoDeploy: true
